version: "3"
services:
  the-codee-cafe-handbook:
    container_name: the-codee-cafe-handbook
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_URL: "git@github.com:odjhey/the-codee-cafe-handbook.git"
    command: "node dist/server.js"
    ports:
      - "7890:8080"
    environment:
      PORT: "8080"
